language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
before-script:
  - cd indi_app_back
script:
  - python manage.py test
  - python manage.py collectstatic --noinput --clear
after-script:
  - cd ..
after-success:
  - pull-request.sh