language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
script:
  - python manage.py test
  - python manage.py collectstatic --noinput --clear
deploy:
  - provider: heroku
    api_key: $HEROKU_API_KEY
    buildpack: heroku/python
    app: staging-back-app
    skip_cleanup: true
    on:
      branch: staging
    run:
      - "python manage.py makemigrations"
      - "python manage.py migrate"
  - provider: heroku
    api_key: $HEROKU_API_KEY
    buildpack: heroku/python
    app: prod-back-app
    skip_cleanup: true
    on:
      branch: master
    run:
      - "python manage.py makemigrations"
      - "python manage.py migrate"