# Generated by Django 2.1.7 on 2021-02-25 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('user', models.CharField(max_length=30)),
                ('category', models.CharField(choices=[('EN', 'Economie'), ('PO', 'Politique'), ('EL', 'Ecologie'), ('NU', 'Numérique'), ('HU', 'Humanités')], max_length=30)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
